---
- hosts: localhost
  tasks:
    - name: Update apt and install required system packages
      apt:
        pkg:
          - autoconf
          - automake
          - coreutils
          - curl
          - gnu-time
          - gpg
          - htop
          - imagemagick@6
          - libtool
          - libxslt
          - libyaml
          - openssl
          - git
          - pkg-config
          - rbenv
          - ruby-build
          - rbenv-default-gems
          - rbenv-gemset
          - readline
          - sqlite3
          - tmux
          - unzip
          - vim
          - zlib
          - zsh
        state: latest
        update_cache: true

    - name: Get the path to ZSH
      become: false
      local_action: command which zsh
      register: zsh_path

    - name: "Ensure zsh is in allowed shells"
      lineinfile:
        path: /etc/shells
        line: "{{ zsh_path.stdout }}"
      become: true

    - name: Install Oh My ZSH
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      args:
        creates: "$HOME/{{ lookup('env', 'USER') }}/.oh-my-zsh"

    - name: Set ZSH as the default shell
      shell: chsh -s $(which zsh) {{ lookup('env', 'USER') }}
      become: true

    - name: Install nvm
      become: no
      shell: >
        curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.39.3/install.sh | bash
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/nvm.sh"

    - name: Install node
      become: no
      shell: >
        . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ item }}
      args:
        executable: /bin/bash
        chdir: "{{ ansible_env.HOME }}"
        creates: "{{ ansible_env.HOME }}/.nvm/versions/{{ item }}"
      loop:
        - 16.15

    - name: "Install Default Ruby"
      shell: |
        rbenv install 3.2.0
        rbenv global 3.2.0
        gem install bundler
        echo 'bundler' >> "$(brew --prefix rbenv)/default-gems"
        echo 'gem: --no-document' >> ~/.gemrc

    - name: Install yarn packages
      shell: yarn global add {{ item }}
      with_items:
        - @angular/cli
        - typescript