---
- hosts: localhost
  tasks:
    - name: Update apt and install required system packages
      apt:
        pkg:
          - autoconf
          - automake
          - coreutils
          - curl
          - gpg
          - htop
          - imagemagick
          - libtool
          - libxslt1-dev
          - libyaml-dev
          - openssl
          - git
          - pkg-config
          - readline-common
          - sqlite3
          - tmux
          - unzip
          - vim
          - zlib1g-dev
          - zsh
        state: latest
        update_cache: true

    - name: Setup ZSH and Oh My ZSH
      import_tasks: tasks/common/zsh.yml

    - name: Setup mise
      import_tasks: tasks/common/mise.yml

    - name: Setup pnpm
      import_tasks: tasks/common/pnpm.yml

    - name: Setup Docker
      import_tasks: tasks/docker.yml

    - name: Setup Google Chrome
      import_tasks: tasks/ubuntu/google-chrome.yml
